language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
#  - "nightly"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy

install:
  - travis_retry pip install -r requirements.txt
# command to run tests
script: python setup.py test
cache: apt